title: Window to World | My Words follow Ellipsis
description: > # this means to ignore newlines until "baseurl:"
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Shaurya Jauhari # add your name
author-img: myself.jpg # add your photo
about-author: I am a Bioinformatician in training with a background in Computer Science. Everyday 
  I go to terms with new facets of Molecular Biology and contemplate the computational
  equivalence. The nature has so designed, that almost every phenomena could possibly
  have a mathematical ground. That is the scope and endeavor of my research. Stay tuned! # add description
social-twitter: shauryajauhari # add your Twitter handle
social-facebook: ishauryajauhari # add your Facebook handle
social-github: shauryajauhari # add your Github handle
social-linkedin: shauryajauhari # add your Linkedin handle
social-email: shauryajauhari@yahoo.com # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
